import type { LocalizedText, ReportScope } from '@swissov/types';

/**
 * Ausgangsbestand der Meldungskategorien (Master-Prompt §2).
 *
 * Dies ist ein **Seed**, keine feste Liste: Kategorien sind über das
 * Admin-Portal anlegbar, änderbar und deaktivierbar (§17/§32). Der Seed ist
 * idempotent — bereits vorhandene Schlüssel werden nicht überschrieben,
 * damit administrative Änderungen bei einem erneuten Lauf erhalten bleiben.
 */
export interface CategorySeed {
  key: string;
  label: LocalizedText;
  description?: LocalizedText;
  /** Ionicons-Name; unbekannte Namen fallen in der App auf ein Standardicon zurück. */
  icon: string;
  color: string;
  group: 'CAPACITY' | 'DISRUPTION' | 'VEHICLE' | 'STATION' | 'SAFETY' | 'INFO' | 'OTHER';
  defaultScope: ReportScope;
  allowedScopes: ReportScope[];
  ttlSeconds: number;
  ttlUntilTripEnd?: boolean;
  requiresTrip?: boolean;
  requiresModeration?: boolean;
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  sortOrder: number;
}

const MIN = 60;
const HOUR = 3600;

export const REPORT_CATEGORY_SEEDS: CategorySeed[] = [
  {
    key: 'ticket_inspection',
    label: {
      de: 'Ticketkontrolle',
      fr: 'Contrôle des billets',
      it: 'Controllo dei biglietti',
      en: 'Ticket inspection',
    },
    description: {
      de: 'Kontrollpersonal ist in dieser Fahrt unterwegs.',
      fr: 'Du personnel de contrôle circule dans ce véhicule.',
      it: 'Il personale di controllo è a bordo di questa corsa.',
      en: 'Inspectors are on board this service.',
    },
    icon: 'ticket-outline',
    color: '#1F6FEB',
    group: 'INFO',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STATION'],
    ttlSeconds: 30 * MIN,
    requiresTrip: false,
    severity: 'LOW',
    sortOrder: 10,
  },
  {
    key: 'very_high_occupancy',
    label: {
      de: 'Sehr hohe Auslastung',
      fr: 'Taux d’occupation très élevé',
      it: 'Occupazione molto elevata',
      en: 'Very high occupancy',
    },
    description: {
      de: 'Fahrzeug ist überfüllt, Zusteigen kaum möglich.',
      fr: 'Véhicule bondé, montée à bord difficile.',
      it: 'Veicolo sovraffollato, salita difficile.',
      en: 'Vehicle is overcrowded, boarding is difficult.',
    },
    icon: 'people',
    color: '#C6303C',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 20 * MIN,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 20,
  },
  {
    key: 'high_occupancy',
    label: {
      de: 'Hohe Auslastung',
      fr: 'Taux d’occupation élevé',
      it: 'Occupazione elevata',
      en: 'High occupancy',
    },
    icon: 'people-outline',
    color: '#E4762E',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 20 * MIN,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 21,
  },
  {
    key: 'limited_space',
    label: {
      de: 'Wenig Platz',
      fr: 'Peu de place',
      it: 'Poco spazio',
      en: 'Limited space',
    },
    icon: 'contract-outline',
    color: '#E0A32E',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 15 * MIN,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 22,
  },
  {
    key: 'delay_mismatch',
    label: {
      de: 'Verspätung weicht von Anzeige ab',
      fr: 'Retard différent de l’affichage',
      it: 'Ritardo diverso dal display',
      en: 'Delay differs from official display',
    },
    description: {
      de: 'Die tatsächliche Verspätung stimmt nicht mit der offiziellen Anzeige überein.',
      fr: 'Le retard réel ne correspond pas à l’affichage officiel.',
      it: 'Il ritardo reale non corrisponde al display ufficiale.',
      en: 'The actual delay does not match the official display.',
    },
    icon: 'time-outline',
    color: '#D4813B',
    group: 'DISRUPTION',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 45 * MIN,
    requiresTrip: false,
    severity: 'MEDIUM',
    sortOrder: 30,
  },
  {
    key: 'unusual_stop',
    label: {
      de: 'Fahrzeug steht ungewöhnlich lange',
      fr: 'Véhicule à l’arrêt anormalement long',
      it: 'Veicolo fermo insolitamente a lungo',
      en: 'Vehicle stopped unusually long',
    },
    icon: 'pause-circle-outline',
    color: '#D4813B',
    group: 'DISRUPTION',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'ROUTE_SEGMENT'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 31,
  },
  {
    key: 'technical_disruption',
    label: {
      de: 'Technische Störung',
      fr: 'Panne technique',
      it: 'Guasto tecnico',
      en: 'Technical disruption',
    },
    icon: 'warning-outline',
    color: '#C6303C',
    group: 'DISRUPTION',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'ROUTE_SEGMENT', 'STATION'],
    ttlSeconds: 60 * MIN,
    severity: 'HIGH',
    sortOrder: 32,
  },
  {
    key: 'vehicle_issue',
    label: {
      de: 'Fahrzeugproblem',
      fr: 'Problème sur le véhicule',
      it: 'Problema del veicolo',
      en: 'Vehicle issue',
    },
    icon: 'construct-outline',
    color: '#B4553C',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 60 * MIN,
    ttlUntilTripEnd: true,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 40,
  },
  {
    key: 'aircon_failure',
    label: {
      de: 'Klimaanlage ausgefallen',
      fr: 'Climatisation en panne',
      it: 'Climatizzazione guasta',
      en: 'Air conditioning failure',
    },
    icon: 'snow-outline',
    color: '#3B8FB4',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 45 * MIN,
    ttlUntilTripEnd: true,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 41,
  },
  {
    key: 'heating_failure',
    label: {
      de: 'Heizung ausgefallen',
      fr: 'Chauffage en panne',
      it: 'Riscaldamento guasto',
      en: 'Heating failure',
    },
    icon: 'flame-outline',
    color: '#B4553C',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 45 * MIN,
    ttlUntilTripEnd: true,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 42,
  },
  {
    key: 'door_defect',
    label: {
      de: 'Tür defekt',
      fr: 'Porte défectueuse',
      it: 'Porta difettosa',
      en: 'Door defect',
    },
    icon: 'exit-outline',
    color: '#B4553C',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 60 * MIN,
    ttlUntilTripEnd: true,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 43,
  },
  {
    key: 'toilet_defect',
    label: {
      de: 'Toilette defekt',
      fr: 'Toilettes hors service',
      it: 'Toilette fuori servizio',
      en: 'Toilet out of order',
    },
    icon: 'water-outline',
    color: '#7A6FA8',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STATION'],
    ttlSeconds: 60 * MIN,
    ttlUntilTripEnd: true,
    severity: 'LOW',
    sortOrder: 44,
  },
  {
    key: 'accessibility_issue',
    label: {
      de: 'Rollstuhlzugang problematisch',
      fr: 'Accès en fauteuil roulant problématique',
      it: 'Accesso in sedia a rotelle problematico',
      en: 'Wheelchair access problem',
    },
    description: {
      de: 'Lift, Rampe oder Einstiegshilfe ist nicht nutzbar.',
      fr: 'Ascenseur, rampe ou aide à l’embarquement inutilisable.',
      it: 'Ascensore, rampa o ausilio di salita non utilizzabile.',
      en: 'Lift, ramp or boarding aid is unusable.',
    },
    icon: 'accessibility-outline',
    color: '#1F6FEB',
    group: 'STATION',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 2 * HOUR,
    severity: 'HIGH',
    sortOrder: 50,
  },
  {
    key: 'station_elevator_defect',
    label: {
      de: 'Lift/Rolltreppe am Bahnhof defekt',
      fr: 'Ascenseur/escalator hors service en gare',
      it: 'Ascensore/scala mobile fuori servizio in stazione',
      en: 'Station lift/escalator out of order',
    },
    icon: 'swap-vertical-outline',
    color: '#1F6FEB',
    group: 'STATION',
    defaultScope: 'STATION',
    allowedScopes: ['STATION', 'STOP'],
    ttlSeconds: 4 * HOUR,
    severity: 'MEDIUM',
    sortOrder: 51,
  },
  {
    key: 'heavy_soiling',
    label: {
      de: 'Starke Verschmutzung',
      fr: 'Forte saleté',
      it: 'Forte sporcizia',
      en: 'Heavy soiling',
    },
    icon: 'trash-outline',
    color: '#6F7B4F',
    group: 'VEHICLE',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 60 * MIN,
    ttlUntilTripEnd: true,
    severity: 'LOW',
    sortOrder: 52,
  },
  {
    key: 'quiet_coach',
    label: {
      de: 'Ruhezone nicht eingehalten',
      fr: 'Zone de silence non respectée',
      it: 'Zona silenzio non rispettata',
      en: 'Quiet zone not respected',
    },
    icon: 'volume-off-outline',
    color: '#7A6FA8',
    group: 'INFO',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 53,
  },
  {
    key: 'luggage_issue',
    label: {
      de: 'Gepäckproblem',
      fr: 'Problème de bagages',
      it: 'Problema con i bagagli',
      en: 'Luggage problem',
    },
    icon: 'briefcase-outline',
    color: '#6F7B4F',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'LOW',
    sortOrder: 54,
  },
  {
    key: 'bike_spaces_full',
    label: {
      de: 'Fahrradplätze voll',
      fr: 'Places vélos complètes',
      it: 'Posti bici esauriti',
      en: 'Bike spaces full',
    },
    icon: 'bicycle-outline',
    color: '#E0A32E',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 55,
  },
  {
    key: 'stroller_spaces_full',
    label: {
      de: 'Kinderwagenplätze voll',
      fr: 'Places poussettes complètes',
      it: 'Posti passeggini esauriti',
      en: 'Stroller spaces full',
    },
    icon: 'walk-outline',
    color: '#E0A32E',
    group: 'CAPACITY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 56,
  },
  {
    key: 'safety_incident',
    label: {
      de: 'Sicherheitsereignis',
      fr: 'Incident de sécurité',
      it: 'Evento di sicurezza',
      en: 'Safety incident',
    },
    description: {
      de: 'Bei akuter Gefahr immer zuerst 112 anrufen.',
      fr: 'En cas de danger immédiat, appelle toujours le 112.',
      it: 'In caso di pericolo immediato, chiama sempre il 112.',
      en: 'In case of immediate danger, always call 112 first.',
    },
    icon: 'shield-outline',
    color: '#C6303C',
    group: 'SAFETY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 60 * MIN,
    requiresModeration: true,
    severity: 'HIGH',
    sortOrder: 60,
  },
  {
    key: 'medical_emergency',
    label: {
      de: 'Medizinischer Notfall',
      fr: 'Urgence médicale',
      it: 'Emergenza medica',
      en: 'Medical emergency',
    },
    description: {
      de: 'Nur als allgemeine Betriebsinformation. Keine Angaben zu betroffenen Personen.',
      fr: 'Uniquement comme information d’exploitation générale. Aucune donnée sur les personnes.',
      it: 'Solo come informazione generale d’esercizio. Nessun dato sulle persone.',
      en: 'General service information only. No details about individuals.',
    },
    icon: 'medkit-outline',
    color: '#C6303C',
    group: 'SAFETY',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STATION'],
    ttlSeconds: 45 * MIN,
    requiresModeration: true,
    severity: 'HIGH',
    sortOrder: 61,
  },
  {
    key: 'emergency_services',
    label: {
      de: 'Polizei-/Rettungseinsatz',
      fr: 'Intervention police/secours',
      it: 'Intervento polizia/soccorso',
      en: 'Police/emergency services operation',
    },
    description: {
      de: 'Nur als allgemeine Betriebsinformation, ohne personenbezogene Angaben.',
      fr: 'Uniquement comme information d’exploitation, sans données personnelles.',
      it: 'Solo come informazione d’esercizio, senza dati personali.',
      en: 'General service information only, without personal data.',
    },
    icon: 'car-sport-outline',
    color: '#C6303C',
    group: 'SAFETY',
    defaultScope: 'STATION',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION', 'ROUTE_SEGMENT'],
    ttlSeconds: 60 * MIN,
    requiresModeration: true,
    severity: 'HIGH',
    sortOrder: 62,
  },
  {
    key: 'lost_item',
    label: {
      de: 'Gegenstand verloren',
      fr: 'Objet perdu',
      it: 'Oggetto smarrito',
      en: 'Lost item',
    },
    icon: 'search-outline',
    color: '#7A6FA8',
    group: 'INFO',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 72 * HOUR,
    severity: 'LOW',
    sortOrder: 70,
  },
  {
    key: 'found_item',
    label: {
      de: 'Gegenstand gefunden',
      fr: 'Objet trouvé',
      it: 'Oggetto trovato',
      en: 'Found item',
    },
    icon: 'cube-outline',
    color: '#6F7B4F',
    group: 'INFO',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 72 * HOUR,
    severity: 'LOW',
    sortOrder: 71,
  },
  {
    key: 'line_interruption',
    label: {
      de: 'Streckenunterbruch',
      fr: 'Interruption de ligne',
      it: 'Interruzione di linea',
      en: 'Line interruption',
    },
    icon: 'close-circle-outline',
    color: '#C6303C',
    group: 'DISRUPTION',
    defaultScope: 'ROUTE_SEGMENT',
    allowedScopes: ['ROUTE_SEGMENT', 'STATION', 'NETWORK'],
    ttlSeconds: 2 * HOUR,
    severity: 'HIGH',
    sortOrder: 80,
  },
  {
    key: 'replacement_service',
    label: {
      de: 'Ersatzverkehr',
      fr: 'Service de remplacement',
      it: 'Servizio sostitutivo',
      en: 'Replacement service',
    },
    icon: 'bus-outline',
    color: '#D4813B',
    group: 'DISRUPTION',
    defaultScope: 'ROUTE_SEGMENT',
    allowedScopes: ['ROUTE_SEGMENT', 'STOP', 'STATION'],
    ttlSeconds: 3 * HOUR,
    severity: 'MEDIUM',
    sortOrder: 81,
  },
  {
    key: 'connection_at_risk',
    label: {
      de: 'Anschluss gefährdet',
      fr: 'Correspondance menacée',
      it: 'Coincidenza a rischio',
      en: 'Connection at risk',
    },
    icon: 'git-branch-outline',
    color: '#E4762E',
    group: 'DISRUPTION',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'STATION'],
    ttlSeconds: 30 * MIN,
    requiresTrip: true,
    severity: 'MEDIUM',
    sortOrder: 82,
  },
  {
    key: 'passenger_info_issue',
    label: {
      de: 'Falsche Fahrgastinformation',
      fr: 'Information voyageurs erronée',
      it: 'Informazione ai viaggiatori errata',
      en: 'Incorrect passenger information',
    },
    description: {
      de: 'Anzeige oder Durchsage ist falsch oder fehlt.',
      fr: 'L’affichage ou l’annonce est erroné ou manquant.',
      it: 'Il display o l’annuncio è errato o mancante.',
      en: 'Display or announcement is wrong or missing.',
    },
    icon: 'information-circle-outline',
    color: '#3B8FB4',
    group: 'INFO',
    defaultScope: 'STATION',
    allowedScopes: ['VEHICLE_TRIP', 'STOP', 'STATION'],
    ttlSeconds: 90 * MIN,
    severity: 'MEDIUM',
    sortOrder: 83,
  },
  {
    key: 'other',
    label: {
      de: 'Sonstige Meldung',
      fr: 'Autre signalement',
      it: 'Altra segnalazione',
      en: 'Other report',
    },
    icon: 'ellipsis-horizontal-circle-outline',
    color: '#6B7280',
    group: 'OTHER',
    defaultScope: 'VEHICLE_TRIP',
    allowedScopes: ['VEHICLE_TRIP', 'ROUTE_SEGMENT', 'STOP', 'STATION'],
    ttlSeconds: 45 * MIN,
    requiresModeration: true,
    severity: 'LOW',
    sortOrder: 999,
  },
];
